version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - '9000:9000'
    volumes:
      - ./backend:/index
      - ./backend:/node_modules
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true